stocks = [
"BBCA.JK","BBRI.JK","BMRI.JK","BBNI.JK","TLKM.JK",
"ASII.JK","UNVR.JK","ICBP.JK","INDF.JK","ANTM.JK",
"MDKA.JK","ADRO.JK","ITMG.JK","PTBA.JK","PGAS.JK",
"CPIN.JK","JPFA.JK","GOTO.JK","BUKA.JK","SMGR.JK",
"INTP.JK","KLBF.JK","SIDO.JK","TOWR.JK","TBIG.JK"
]
